win-mdc:
	g++ -O2 -std=c++20 mdc.cpp -o mdc
	./mdc
	rm mdc

win-merge_sort:
	g++ -O2 -std=c++20 merge_sort.cpp -o merge_sort
	./merge_sort
	rm merge_sort

win-primos:
	g++ -O2 -std=c++20 primos.cpp -o primos
	./primos
	rm primos

win-matriz:
	g++ -O2 -std=c++20 matriz.cpp -o matriz
	./matriz
	rm matriz

unix-mdc:
	g++ -O2 -std=c++20 mdc.cpp -o mdc
	./mdc
	rm mdc

unix-merge_sort:
	g++ -O2 -std=c++20 merge_sort.cpp -o merge_sort
	./merge_sort
	rm merge_sort

unix-primos:
	g++ -O2 -std=c++20 primos.cpp -o primos
	./primos
	rm primos

unix-matriz:
	g++ -O2 -std=c++20 matriz.cpp -o matriz
	./matriz
	rm matriz
