win:
	g++ -std=c++23 -O2 main.cpp -o main
	main < input.txt

win-run:
	main < input.txt

win-del:
	del main.exe

unix:
	g++ -std=c++23 -O2 main.cpp -o main
	./main < input.txt

unix-run:
	./main < input.txt

unix-rm:
	rm main
