# WIN
win-math:
	g++ -O2 -std=c++20 math.cpp -o math
	math
	del math.exe

win-matriz:
	g++ -O2 -std=c++20 matriz.cpp -o matriz
	matriz
	del matriz.exe

win-sort:
	g++ -O2 -std=c++20 sort.cpp -o sort
	sort
	del sort.exe

win-primos:
	g++ -O2 -std=c++20 primos.cpp -o primos
	primos
	del primos.exe

win-coprimos:
	g++ -O2 -std=c++20 coprimos.cpp -o coprimos
	coprimos
	del coprimos.exe

win-perfeito:
	g++ -O2 -std=c++20 perfeito.cpp -o perfeito
	perfeito
	del perfeito.exe

# UNIX
unix-math:
	g++ -O2 -std=c++20 math.cpp -o math
	./math
	rm math

unix-matriz:
	g++ -O2 -std=c++20 matriz.cpp -o matriz
	./matriz
	rm matriz

unix-sort:
	g++ -O2 -std=c++20 sort.cpp -o sort
	./sort
	rm sort

unix-primos:
	g++ -O2 -std=c++20 primos.cpp -o primos
	./primos
	rm primos

unix-coprimos:
	g++ -O2 -std=c++20 coprimos.cpp -o coprimos
	./coprimos
	rm coprimos

unix-perfeito:
	g++ -O2 -std=c++20 perfeito.cpp -o perfeito
	./perfeito
	rm perfeito