win:
	g++ -std=c++20 -O2 main.cpp -o main -I ../../../
	main

win-run:
	main

win-del:
	del main.exe

unix:
	g++ -std=c++20 -O2 main.cpp -o main -I ../../../
	./main

unix-run:
	./main

unix-rm:
	rm main
